server:
  port: 9090
  tomcat:
    uri-encoding: utf-8

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/yh?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
#  redis:
#    port: 6379
#    host: 192.168.1.102
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yh.pojo
logging:
  file:
    path: d:/log.txt
  level:
    com.yh: debug
